name: CI/CD for Node.js Docker Compose App

on:
  push:
    branches:
      - server

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.0
        env:
          WB_API_KEY: ${{ secrets.WB_API_KEY }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          envs: WB_API_KEY,DB_USER,DB_PORT,DB_PASS,DB_HOST,DB_DATABASE
          script: |
            cd /opt/loader
            git pull origin server
            docker compose down
            docker compose up -d --build
